spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/hajsback_auth

session:
  duration: 3600

activemq:
  host: "localhost"
  user: "hajsback"
  pass: "secr3t"

security:
  secret: "secret"