version: '3'

volumes:
  mongo-vol:

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - "mongo-vol:/data/db"

  mq:
    container_name: mq
    image: webcenter/activemq
    environment:
      ACTIVEMQ_OWNER_LOGIN: hajsback
      ACTIVEMQ_OWNER_PASSWORD: secr3t
      ACTIVEMQ_LOGLEVEL: DEBUG
    expose:
      - "61616"
      - "8161"
    ports:
      - "61616:61616"
      - "8161:8161"
