version: '2'

services:
  mongodb:
    container_name: mongodb
    image: mongo:3.2
    ports:
      - '27017:27017'

  mq:
    container_name: mq
    image: webcenter/activemq
    environment:
      ACTIVEMQ_OWNER_LOGIN: hajsback
      ACTIVEMQ_OWNER_PASSWORD: secr3t
      ACTIVEMQ_LOGLEVEL: DEBUG
    expose:
      - "61616"
      - "8161"
    ports:
      - "61616:61616"
      - "8161:8161"